class Player():
    """
    Player class that represents each player.
    """

    def __init__(self, gold, score, gold_per_turn, deck, hand):
        """
        :type self: Player
        :type gold: int
        :type score: int
        :type gold_per_turn: int
        :type deck: Deck
        :type hand: Hand

        :param gold: The amount of gold in the player's bank
        :param score: The player's current score
        :param gold_per_turn: The amount of gold generated by the player's network each turn.
        :param deck: The player's deck
        :param hand: The cards currently available for the player to use
        """

        self.gold = gold
        self.score = score
        self.gold_per_turn = gold_per_turn
        self.deck = deck
        self.hand = hand

    def update(self):
        """
        This handles the updating of any attributes of an instance of Player at the change of a turn

        :type self: Player
        """
        self.gold += self.gold_per_turn

        self.hand.add(self.deck.pop)
        self.hand.add(self.deck.pop)

        while self.hand.size > 7:
            self.hand.discard()
